// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"wk-middleground/health_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chatgpt/chatget",
				Handler: ChatGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chatgpt/chatlist",
				Handler: ChatListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/equipment/bind",
				Handler: EquipmentBindHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/statistics/result",
				Handler: StatisticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/score/getNum",
				Handler: ScoreHandler(serverCtx),
			},
		},
	)
}
