// Code generated by goctl. DO NOT EDIT.
// Source: score.proto

package server

import (
	"context"

	"wk-middleground/score_srv/internal/logic"
	"wk-middleground/score_srv/internal/svc"
	__ "wk-middleground/score_srv/pb"
)

type ScoreServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedScoreServer
}

func NewScoreServer(svcCtx *svc.ServiceContext) *ScoreServer {
	return &ScoreServer{
		svcCtx: svcCtx,
	}
}

func (s *ScoreServer) Create(ctx context.Context, in *__.CreateReq) (*__.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ScoreServer) Update(ctx context.Context, in *__.UpdateReq) (*__.CreateResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ScoreServer) DtmCreate(ctx context.Context, in *__.CreateReq) (*__.CreateResp, error) {
	l := logic.NewDtmCreateLogic(ctx, s.svcCtx)
	return l.DtmCreate(in)
}

func (s *ScoreServer) DtmRollback(ctx context.Context, in *__.CreateReq) (*__.CreateResp, error) {
	l := logic.NewDtmRollbackLogic(ctx, s.svcCtx)
	return l.DtmRollback(in)
}

func (s *ScoreServer) GetScore(ctx context.Context, in *__.GetReq) (*__.GetResp, error) {
	l := logic.NewGetScoreLogic(ctx, s.svcCtx)
	return l.GetScore(in)
}
