// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: equipment.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EquipmentId string  `protobuf:"bytes,2,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`
	Bpm         float64 `protobuf:"fixed64,3,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Pi          float64 `protobuf:"fixed64,4,opt,name=pi,proto3" json:"pi,omitempty"`
	Spo2        float64 `protobuf:"fixed64,5,opt,name=spo2,proto3" json:"spo2,omitempty"`
	Gluecose    float64 `protobuf:"fixed64,6,opt,name=gluecose,proto3" json:"gluecose,omitempty"`
}

func (x *EquipmentRequest) Reset() {
	*x = EquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRequest) ProtoMessage() {}

func (x *EquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRequest.ProtoReflect.Descriptor instead.
func (*EquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{0}
}

func (x *EquipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EquipmentRequest) GetEquipmentId() string {
	if x != nil {
		return x.EquipmentId
	}
	return ""
}

func (x *EquipmentRequest) GetBpm() float64 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *EquipmentRequest) GetPi() float64 {
	if x != nil {
		return x.Pi
	}
	return 0
}

func (x *EquipmentRequest) GetSpo2() float64 {
	if x != nil {
		return x.Spo2
	}
	return 0
}

func (x *EquipmentRequest) GetGluecose() float64 {
	if x != nil {
		return x.Gluecose
	}
	return 0
}

type BindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipmentId string `protobuf:"bytes,1,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`
	DataId      string `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{1}
}

func (x *BindRequest) GetEquipmentId() string {
	if x != nil {
		return x.EquipmentId
	}
	return ""
}

func (x *BindRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type UpEqpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UpEqpRequest) Reset() {
	*x = UpEqpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpEqpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpEqpRequest) ProtoMessage() {}

func (x *UpEqpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpEqpRequest.ProtoReflect.Descriptor instead.
func (*UpEqpRequest) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{2}
}

func (x *UpEqpRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EquipmentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 设备id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名称
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 设备型号
	TypeId string `protobuf:"bytes,3,opt,name=TypeId,proto3" json:"TypeId,omitempty"`
	// 设备数据
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EquipmentData) Reset() {
	*x = EquipmentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentData) ProtoMessage() {}

func (x *EquipmentData) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentData.ProtoReflect.Descriptor instead.
func (*EquipmentData) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EquipmentData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EquipmentData) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *EquipmentData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EquipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*EquipmentData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *EquipmentResponse) Reset() {
	*x = EquipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentResponse) ProtoMessage() {}

func (x *EquipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentResponse.ProtoReflect.Descriptor instead.
func (*EquipmentResponse) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{4}
}

func (x *EquipmentResponse) GetData() []*EquipmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResRequest) Reset() {
	*x = ResRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRequest) ProtoMessage() {}

func (x *ResRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRequest.ProtoReflect.Descriptor instead.
func (*ResRequest) Descriptor() ([]byte, []int) {
	return file_equipment_proto_rawDescGZIP(), []int{5}
}

var File_equipment_proto protoreflect.FileDescriptor

var file_equipment_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9e, 0x01, 0x0a, 0x10, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x70, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x62, 0x70, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x69, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x02, 0x70, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x73, 0x70, 0x6f, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6c,
	0x75, 0x65, 0x63, 0x6f, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x67, 0x6c,
	0x75, 0x65, 0x63, 0x6f, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x22,
	0x22, 0x0a, 0x0c, 0x55, 0x70, 0x45, 0x71, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x11, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x32, 0xdc, 0x01, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x45, 0x71, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x62,
	0x69, 0x6e, 0x64, 0x45, 0x71, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x75,
	0x70, 0x58, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31,
	0x0a, 0x09, 0x75, 0x70, 0x58, 0x79, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_equipment_proto_rawDescOnce sync.Once
	file_equipment_proto_rawDescData = file_equipment_proto_rawDesc
)

func file_equipment_proto_rawDescGZIP() []byte {
	file_equipment_proto_rawDescOnce.Do(func() {
		file_equipment_proto_rawDescData = protoimpl.X.CompressGZIP(file_equipment_proto_rawDescData)
	})
	return file_equipment_proto_rawDescData
}

var file_equipment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_equipment_proto_goTypes = []interface{}{
	(*EquipmentRequest)(nil),  // 0: pb.EquipmentRequest
	(*BindRequest)(nil),       // 1: pb.BindRequest
	(*UpEqpRequest)(nil),      // 2: pb.UpEqpRequest
	(*EquipmentData)(nil),     // 3: pb.EquipmentData
	(*EquipmentResponse)(nil), // 4: pb.EquipmentResponse
	(*ResRequest)(nil),        // 5: pb.ResRequest
}
var file_equipment_proto_depIdxs = []int32{
	3, // 0: pb.EquipmentResponse.data:type_name -> pb.EquipmentData
	0, // 1: pb.Equipment.getEqpData:input_type -> pb.EquipmentRequest
	1, // 2: pb.Equipment.bindEqpData:input_type -> pb.BindRequest
	0, // 3: pb.Equipment.upXtyData:input_type -> pb.EquipmentRequest
	0, // 4: pb.Equipment.upXyyData:input_type -> pb.EquipmentRequest
	4, // 5: pb.Equipment.getEqpData:output_type -> pb.EquipmentResponse
	5, // 6: pb.Equipment.bindEqpData:output_type -> pb.ResRequest
	5, // 7: pb.Equipment.upXtyData:output_type -> pb.ResRequest
	5, // 8: pb.Equipment.upXyyData:output_type -> pb.ResRequest
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_equipment_proto_init() }
func file_equipment_proto_init() {
	if File_equipment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_equipment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpEqpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_equipment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_equipment_proto_goTypes,
		DependencyIndexes: file_equipment_proto_depIdxs,
		MessageInfos:      file_equipment_proto_msgTypes,
	}.Build()
	File_equipment_proto = out.File
	file_equipment_proto_rawDesc = nil
	file_equipment_proto_goTypes = nil
	file_equipment_proto_depIdxs = nil
}
