// Code generated by goctl. DO NOT EDIT.
package types

type ChatGetRequest struct {
	UserId   int64  `json:"userId"`
	Question string `json:"question"`
}

type ChatGetResponse struct {
	Answer string `json:"answer"`
}

type ChatListRequest struct {
	UserId int64 `json:"userId"`
}

type ChatListResponse struct {
	Answers []string `json:"answers"`
}

type EquipmentBindRequest struct {
	UserId int64   `json:"userId"`
	DataId int64   `json:"dataId"`
	Score  float64 `json:"score"`
}

type EquipmentBindResponse struct {
	IsBind bool `json:"isBind"`
}

type StatisticsRequest struct {
	UserId int64 `json:"userId"`
}

type StatisticsResponse struct {
	Statistics []string `json:"statistics"`
}

type ScoreRequest struct {
	UserId int64 `json:"userId"`
}

type CreateScoreRequest struct {
	UserId int64   `json:"userId"`
	Score  float64 `json:"score"`
}

type ScoreResponse struct {
	Score int64 `json:"score"`
}
