// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scoreFieldNames          = builder.RawFieldNames(&Score{})
	scoreRows                = strings.Join(scoreFieldNames, ",")
	scoreRowsExpectAutoSet   = strings.Join(stringx.Remove(scoreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scoreRowsWithPlaceHolder = strings.Join(stringx.Remove(scoreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	scoreModel interface {
		Insert(ctx context.Context, data *Score) (sql.Result, error)
		DtmInsert(tx *sql.Tx, data *Score) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Score, error)
		FindByUserId(ctx context.Context, id int64) (*Score, error)
		Update(ctx context.Context, data *Score) error
		DtmUpdate(tx *sql.Tx, data *Score) (sql.Result, error)
		Delete(ctx context.Context, id int64) error
	}

	defaultScoreModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Score struct {
		Id        int64        `db:"id"`
		CreatedAt sql.NullTime `db:"created_at"`
		UpdatedAt sql.NullTime `db:"updated_at"`
		DeletedAt sql.NullTime `db:"deleted_at"`
		UserId    int64        `db:"user_id"`    // 用户id
		Score     float64      `db:"score"`      // 积分
		CreatedBy int64        `db:"created_by"` // 创建者
	}
)

func newScoreModel(conn sqlx.SqlConn) *defaultScoreModel {
	return &defaultScoreModel{
		conn:  conn,
		table: "`score`",
	}
}

func (m *defaultScoreModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultScoreModel) FindOne(ctx context.Context, id int64) (*Score, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scoreRows, m.table)
	var resp Score

	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) FindByUserId(ctx context.Context, id int64) (*Score, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", scoreRows, m.table)
	var resp Score
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) Insert(ctx context.Context, data *Score) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, scoreRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.Score, data.CreatedBy)
	return ret, err
}

func (m *defaultScoreModel) Update(ctx context.Context, data *Score) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scoreRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.Score, data.CreatedBy, data.Id)
	return err
}
func (m *defaultScoreModel) DtmInsert(tx *sql.Tx, data *Score) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, scoreRowsExpectAutoSet)
	//logx.Info("data.score:", data.Score)
	return tx.Exec(query, data.CreatedAt, data.UserId, data.Score, data.CreatedBy)
}

func (m *defaultScoreModel) DtmUpdate(tx *sql.Tx, data *Score) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scoreRowsWithPlaceHolder)
	return tx.Exec(query, data.DeletedAt, data.UserId, data.Score, data.CreatedBy, data.Id)
}

func (m *defaultScoreModel) tableName() string {
	return m.table
}
